# 站点名称
site_name: 'GitGuide'
# 仓库链接
repo_url: https://github.com/ZJDoc/GitGuide.git
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true
    # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - 规范:
      - GIT工作流: workflow/index.md
      - README:
        - 引言: readme/index.md
        - '[译]规范': readme/译-规范.md
        - '徽章': readme/badge.md
        - 后记: readme/postscript.md
      - MESSAGE:
        - 引言: message/index.md
        - '[gitmessage]提交模板': message/gitmessage.md
        - 'Conventional提交规范': message/conventional-commit.md
        - 'Angular提交规范': message/angular-commit.md
      - VERSION: version/semver.md
    - 工具:
      - Git:
        - 引言: git/index.md
        - Base:
          - 关于版本控制: git/base/关于版本控制.md
          - 工作区域: git/base/工作区域.md
          - '[git config]配置': git/base/git-config.md
          - 获取git仓库: git/base/获取git仓库.md
          - 提交新版本: git/base/提交新版本.md
          - '[git log]日志查询': git/base/git-log.md
          - 标签设置: git/base/标签设置.md
          - '.gitkeep': git/base/gitkeep.md
          - 子模块: git/base/子模块.md
          - '[ssh][http]传输方式切换': git/base/ssh-http-传输方式切换.md